import type { Deal } from "@/types";

export const DEMO_DEALS: Deal[] = [
  {
    id: "d1",
    slug: "luxury-thai-spa-package-gulshan",
    title: "Luxury Thai Spa Package — Full Body Massage with Aromatherapy & Hot Stones",
    description: "Indulge in a premium spa experience with authentic Thai techniques.",
    highlights: ["60-min full body massage", "Aromatherapy included", "Hot stone therapy", "Refreshments included"],
    images: ["/images/deals/spa-1.jpg"],
    originalPrice: 5000,
    dealPrice: 1999,
    discountPercent: 60,
    extraDiscount: 200,
    extraDiscountLabel: "Extra ৳200 off, ends tomorrow",
    quantityTotal: 500,
    quantitySold: 3420,
    maxPerUser: 3,
    startDate: "2026-04-01",
    endDate: "2026-05-15",
    status: "active",
    isFeatured: true,
    isSponsored: false,
    viewCount: 12500,
    ratingAvg: 4.7,
    ratingCount: 2341,
    merchant: { id: "m1", businessName: "Serenity Thai Spa", address: "House 45, Road 12", area: "Gulshan", city: "Dhaka", latitude: 23.7801, longitude: 90.4162, distanceKm: 2.3, isVerified: true, ratingAvg: 4.7, ratingCount: 2341 },
    category: { id: "beauty", name: "Beauty & Spa", slug: "beauty-and-spa" },
    options: [
      { id: "o1", title: "60-Min Thai Massage", originalPrice: 5000, dealPrice: 1999, boughtCount: 2100 },
      { id: "o2", title: "90-Min Royal Package", originalPrice: 7500, dealPrice: 2999, boughtCount: 1320 },
    ],
    badges: ["popular", "verified"],
  },
  {
    id: "d2",
    slug: "premium-sushi-platter-banani",
    title: "Premium Sushi & Ramen Platter for Two — 20pc Sushi + 2 Signature Ramen Bowls",
    description: "Experience authentic Japanese dining with the freshest ingredients.",
    highlights: ["20pc mixed sushi platter", "2 bowls signature ramen", "Complimentary green tea", "Dine-in only"],
    images: ["/images/deals/food-1.jpg"],
    originalPrice: 3500,
    dealPrice: 1499,
    discountPercent: 57,
    quantityTotal: 300,
    quantitySold: 890,
    maxPerUser: 5,
    startDate: "2026-04-01",
    endDate: "2026-04-30",
    status: "active",
    isFeatured: true,
    isSponsored: false,
    viewCount: 8900,
    ratingAvg: 4.5,
    ratingCount: 567,
    merchant: { id: "m2", businessName: "Tokyo Ramen House", address: "Road 11, Block D", area: "Banani", city: "Dhaka", latitude: 23.7940, longitude: 90.4043, distanceKm: 3.1, isVerified: true, ratingAvg: 4.5, ratingCount: 567 },
    category: { id: "food", name: "Food & Drink", slug: "food-and-drink" },
    options: [
      { id: "o3", title: "Sushi Platter for Two", originalPrice: 3500, dealPrice: 1499, boughtCount: 650 },
      { id: "o4", title: "Premium Omakase for Two", originalPrice: 6000, dealPrice: 2799, boughtCount: 240 },
    ],
    badges: ["popular", "gift"],
  },
  {
    id: "d3",
    slug: "laser-hair-removal-dhanmondi",
    title: "6 Sessions Laser Hair Removal — Full Body or Targeted Areas (Up to 78% Off)",
    description: "FDA-approved laser technology for permanent hair reduction.",
    highlights: ["6 sessions included", "FDA-approved laser", "Licensed practitioners", "All skin types"],
    images: ["/images/deals/beauty-1.jpg"],
    originalPrice: 25000,
    dealPrice: 5499,
    discountPercent: 78,
    quantityTotal: 200,
    quantitySold: 1560,
    maxPerUser: 2,
    startDate: "2026-04-01",
    endDate: "2026-06-30",
    status: "active",
    isFeatured: false,
    isSponsored: true,
    viewCount: 15000,
    ratingAvg: 4.8,
    ratingCount: 1230,
    merchant: { id: "m3", businessName: "GlowDerm Clinic", address: "House 7, Road 4", area: "Dhanmondi", city: "Dhaka", latitude: 23.7461, longitude: 90.3742, distanceKm: 1.5, isVerified: true, ratingAvg: 4.8, ratingCount: 1230 },
    category: { id: "beauty", name: "Beauty & Spa", slug: "beauty-and-spa" },
    options: [
      { id: "o5", title: "Full Body — 6 Sessions", originalPrice: 25000, dealPrice: 5499, boughtCount: 980 },
      { id: "o6", title: "Underarms + Bikini — 6 Sessions", originalPrice: 12000, dealPrice: 2999, boughtCount: 580 },
    ],
    badges: ["sponsored", "verified"],
  },
  {
    id: "d4",
    slug: "escape-room-adventure-uttara",
    title: "Thrilling Escape Room Experience for 4 — Choose from 5 Themed Rooms",
    description: "Test your wits in Dhaka's most immersive escape room adventures!",
    highlights: ["60 mins gameplay", "Teams of 2-6", "5 themed rooms", "Photo opportunity included"],
    images: ["/images/deals/activity-1.jpg"],
    originalPrice: 4000,
    dealPrice: 1599,
    discountPercent: 60,
    quantityTotal: 100,
    quantitySold: 2780,
    maxPerUser: 4,
    startDate: "2026-04-01",
    endDate: "2026-05-31",
    status: "active",
    isFeatured: true,
    isSponsored: false,
    viewCount: 9200,
    ratingAvg: 4.6,
    ratingCount: 890,
    merchant: { id: "m4", businessName: "MindLock Adventures", address: "Sector 10", area: "Uttara", city: "Dhaka", latitude: 23.8759, longitude: 90.3950, distanceKm: 8.2, isVerified: true, ratingAvg: 4.6, ratingCount: 890 },
    category: { id: "activities", name: "Activities", slug: "things-to-do" },
    options: [
      { id: "o7", title: "Standard Room — 4 Players", originalPrice: 4000, dealPrice: 1599, boughtCount: 1800 },
      { id: "o8", title: "Premium Room — 4 Players", originalPrice: 6000, dealPrice: 2499, boughtCount: 980 },
    ],
    badges: ["popular"],
  },
  {
    id: "d5",
    slug: "full-car-detailing-mirpur",
    title: "Complete Car Detailing Package — Interior + Exterior + Ceramic Coating",
    description: "Professional auto detailing using premium products.",
    highlights: ["Interior deep clean", "Exterior wash & polish", "Ceramic coating", "Tire dressing"],
    images: ["/images/deals/auto-1.jpg"],
    originalPrice: 8000,
    dealPrice: 2999,
    discountPercent: 63,
    quantityTotal: 150,
    quantitySold: 670,
    maxPerUser: 3,
    startDate: "2026-04-01",
    endDate: "2026-05-15",
    status: "active",
    isFeatured: false,
    isSponsored: false,
    viewCount: 4500,
    ratingAvg: 4.4,
    ratingCount: 345,
    merchant: { id: "m5", businessName: "ShineMax Auto Care", address: "Section 12", area: "Mirpur", city: "Dhaka", latitude: 23.8223, longitude: 90.3654, distanceKm: 6.4, isVerified: true, ratingAvg: 4.4, ratingCount: 345 },
    category: { id: "auto", name: "Auto & Home", slug: "auto-and-home" },
    options: [
      { id: "o9", title: "Standard Detailing", originalPrice: 5000, dealPrice: 1999, boughtCount: 420 },
      { id: "o10", title: "Premium + Ceramic", originalPrice: 8000, dealPrice: 2999, boughtCount: 250 },
    ],
    badges: ["verified"],
  },
  {
    id: "d6",
    slug: "couples-cooking-class-dhanmondi",
    title: "Italian Pasta & Pizza Cooking Class for Two — Hands-On Experience with Chef",
    description: "Learn to make authentic Italian dishes from a professional chef.",
    highlights: ["3-hour class", "All ingredients included", "Wine tasting", "Recipe booklet to take home"],
    images: ["/images/deals/class-1.jpg"],
    originalPrice: 6000,
    dealPrice: 2499,
    discountPercent: 58,
    quantityTotal: 80,
    quantitySold: 340,
    maxPerUser: 2,
    startDate: "2026-04-01",
    endDate: "2026-05-31",
    status: "active",
    isFeatured: true,
    isSponsored: false,
    viewCount: 6700,
    ratingAvg: 4.9,
    ratingCount: 215,
    merchant: { id: "m6", businessName: "Chef's Table Academy", address: "Road 27", area: "Dhanmondi", city: "Dhaka", latitude: 23.7541, longitude: 90.3762, distanceKm: 2.0, isVerified: true, ratingAvg: 4.9, ratingCount: 215 },
    category: { id: "activities", name: "Activities", slug: "things-to-do" },
    options: [
      { id: "o11", title: "Couples Class (2 persons)", originalPrice: 6000, dealPrice: 2499, boughtCount: 280 },
      { id: "o12", title: "Group Class (4 persons)", originalPrice: 10000, dealPrice: 3999, boughtCount: 60 },
    ],
    badges: ["popular", "gift"],
  },
  {
    id: "d7",
    slug: "dental-checkup-cleaning-motijheel",
    title: "Complete Dental Checkup + Professional Cleaning + X-Ray — Smile Bright!",
    description: "Comprehensive dental care package at a top-rated clinic.",
    highlights: ["Full checkup", "Professional scaling & polishing", "Panoramic X-ray", "Free consultation"],
    images: ["/images/deals/health-1.jpg"],
    originalPrice: 3000,
    dealPrice: 899,
    discountPercent: 70,
    quantityTotal: 300,
    quantitySold: 4500,
    maxPerUser: 2,
    startDate: "2026-04-01",
    endDate: "2026-06-30",
    status: "active",
    isFeatured: false,
    isSponsored: false,
    viewCount: 18000,
    ratingAvg: 4.6,
    ratingCount: 3200,
    merchant: { id: "m7", businessName: "SmileCare Dental", address: "Dilkusha C/A", area: "Motijheel", city: "Dhaka", latitude: 23.7258, longitude: 90.4131, distanceKm: 4.1, isVerified: true, ratingAvg: 4.6, ratingCount: 3200 },
    category: { id: "health", name: "Health & Fitness", slug: "health-and-fitness" },
    options: [
      { id: "o13", title: "Basic Checkup + Cleaning", originalPrice: 3000, dealPrice: 899, boughtCount: 3200 },
      { id: "o14", title: "Whitening + Checkup", originalPrice: 8000, dealPrice: 2499, boughtCount: 1300 },
    ],
    badges: ["popular", "verified"],
  },
  {
    id: "d8",
    slug: "gym-membership-bashundhara",
    title: "3-Month Premium Gym Membership — Full Access + Personal Trainer Session",
    description: "Get fit with world-class equipment and expert trainers.",
    highlights: ["3-month unlimited access", "1 free PT session", "Sauna & steam access", "Locker included"],
    images: ["/images/deals/fitness-1.jpg"],
    originalPrice: 15000,
    dealPrice: 4999,
    discountPercent: 67,
    quantityTotal: 200,
    quantitySold: 890,
    maxPerUser: 1,
    startDate: "2026-04-01",
    endDate: "2026-05-15",
    status: "active",
    isFeatured: true,
    isSponsored: false,
    viewCount: 7800,
    ratingAvg: 4.3,
    ratingCount: 678,
    merchant: { id: "m8", businessName: "FitZone Premium", address: "Block B", area: "Bashundhara", city: "Dhaka", latitude: 23.8201, longitude: 90.4282, distanceKm: 5.5, isVerified: true, ratingAvg: 4.3, ratingCount: 678 },
    category: { id: "health", name: "Health & Fitness", slug: "health-and-fitness" },
    options: [
      { id: "o15", title: "3-Month Membership", originalPrice: 15000, dealPrice: 4999, boughtCount: 620 },
      { id: "o16", title: "6-Month Membership", originalPrice: 25000, dealPrice: 7999, boughtCount: 270 },
    ],
    badges: ["limited"],
  },
];
